version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "amicell-infrastructure"
s3_prefix = "amicell-infrastructure"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2oypo5ttul5c"
